import { PromptBuilder } from "./core/prompt-builder.ts"

// Runtime-managed file. It is automatically replaced on startup; do not edit manually.
const builder = new PromptBuilder()

function managedContractBlock() {
  return `\
# Managed Harness API Contract

This prompt section is runtime-managed and overwritten on startup.
Do not edit this file manually; local edits will be replaced automatically.

Priority rule:
- If any other prompt file conflicts with this contract about runtime APIs, service manifests, event streams, or routing behavior, this contract wins.

Scope:
- Use this section as the source of truth for task APIs, service lifecycle, and service-to-agent wiring.
- Use other prompt files for style, domain behavior, memory strategy, and task-specific policies.`
}

function taskApiBlock() {
  return `\
# core/api task primitives

\`core/api\` functions and expected behavior:

- \`createAgent({ id?, system?, model?, source? })\`
Creates or upserts an agent task. Safe to call on every restart.

- \`sendInput(taskId, message, opts?)\`
Sends input to a task. For agent tasks, this delivers a user message.
\`sendInput\` returns \`{ ok, request_id?, service_id? }\` and the \`request_id\` is the primary correlation key for replies.
\`opts\`:
  - \`source?\`, \`priority?\`, \`request_id?\`
  - \`service_id?\`
  - \`context?\` object
When called inside a service process, \`sendInput\` automatically injects \`context.service_id\` from \`GO_AGENTS_SERVICE_ID\` unless explicitly provided.
\`service_id\` is authoritative routing identity and is never inferred from \`source\`.

- \`getUpdates(taskId, { kind?, after_id?, limit? })\`
Fetches task updates (including \`assistant_output\`, \`stdout\`, \`stderr\`, \`completed\`, \`failed\`).

- \`assistantOutputRoutes(payload)\`
Normalizes assistant output routing metadata into a deterministic list of route candidates.
Uses \`payload.routes\` only.

- \`subscribe({ streams?: string[] })\`
Returns an object with \`events\` (async iterable) and \`close()\`.
Consume with:
\`\`\`ts
const sub = subscribe({ streams: ["task_output", "errors"] })
for await (const evt of sub.events) {
  // ...
}
\`\`\``
}

function servicesContractBlock() {
  return `\
# Service manifest contract

Services live in \`services/<name>/\` and must include \`service.json\`.

Canonical manifest shape:
\`\`\`json
{
  "service_id": "my-service",
  "singleton": true,
  "environment": {
    "MY_API_TOKEN": "replace-me"
  },
  "required_env": ["MY_API_TOKEN"],
  "restart": {
    "policy": "always",
    "min_backoff_ms": 1000,
    "max_backoff_ms": 60000
  },
  "health": {
    "heartbeat_file": ".heartbeat",
    "heartbeat_ttl_seconds": 120,
    "restart_on_stale": true
  }
}
\`\`\`

Rules:
- One integration account/token should map to one service directory and one \`service_id\` (singleton pattern).
- Reuse and update the same service instead of creating siblings with near-duplicate behavior.
- Service secrets/config belong in \`service.json.environment\`, not \`~/.go-agents/.env\`.
- \`required_env\` validates runtime readiness. Missing values block startup instead of crash-looping.
- \`service_id\` is explicit identity; do not infer it from guesses in free text.`
}

function bridgePatternBlock() {
  return `\
# Generic request/reply bridge pattern

For external messaging or polling integrations, use two explicit flows:

1) Inbound flow (external -> agent):
- Poll or receive external messages.
- Normalize payload.
- \`sendInput(agentId, text, { context })\` with stable routing fields (for example \`channel_id\`, \`thread_id\`, \`service_id\`).

2) Outbound flow (agent -> external):
- Read agent outputs via task updates or stream events.
- Route back using context/request metadata captured from inbound messages.

Minimal resilient shape:
\`\`\`ts
import { createAgent, getUpdates, sendInput, assistantOutputRoutes } from "core/api"

const agentId = "operator"
await createAgent({ id: agentId, system: "You are a helpful assistant." })

let lastAssistantUpdateId: string | undefined
const pendingRoutes = new Map<string, Record<string, unknown>>()

while (true) {
  // inbound: external -> sendInput(...)
  // Example:
  // const route = { namespace: "service", conversation_id: "abc123", channel_id: "..." }
  // const sent = await sendInput(agentId, inboundText, { context: route })
  // if (sent.request_id) pendingRoutes.set(sent.request_id, route)

  // outbound: poll assistant_output updates
  const updates = await getUpdates(agentId, {
    kind: "assistant_output",
    after_id: lastAssistantUpdateId,
    limit: 100,
  })
  for (const u of updates) {
    lastAssistantUpdateId = u.id
    const payload = u.payload || {}
    const text = typeof payload.text === "string" ? payload.text : ""
    if (text.trim() === "") continue

    // Deterministic routing even when one assistant turn bundles multiple inbound events.
    const routeCandidates = assistantOutputRoutes(payload as Record<string, unknown>)
    for (const route of routeCandidates) {
      const routeRequestId = typeof route.request_id === "string" ? route.request_id : ""
      const routeContext = (route.context && typeof route.context === "object")
        ? route.context as Record<string, unknown>
        : {}
      const resolved = routeRequestId !== "" ? (pendingRoutes.get(routeRequestId) || routeContext) : routeContext
      // externalSend(resolved, text)
      if (routeRequestId !== "") pendingRoutes.delete(routeRequestId)
    }
  }

  await Bun.write(".heartbeat", new Date().toISOString())
  await Bun.sleep(1000)
}
\`\`\`

Do not assume plain assistant text is auto-delivered to external channels.
Delivery to external systems only happens when bridge code explicitly sends it.`
}

function outputRoutingBlock() {
  return `\
# Output routing semantics

- Agent replies are emitted as task updates with kind \`assistant_output\`.
- Related bus events appear on \`task_output\` with metadata (for example \`task_kind=assistant_output\`).
- For deterministic request/reply delivery at scale, correlate by \`request_id\`, not arrival order.
- \`assistant_output\` includes \`text\` and \`routes\` for deterministic routing.
- \`assistant_output.routes\` includes all routing candidates observed during that LLM turn as \`{ request_id?, context? }\`, so bundled events do not drop correlation data.`
}

function routingStrategyBlock() {
  return `\
# Conversation routing strategies

Pick one strategy per integration and switch dynamically when needed:

1) Single operator + request correlation:
- One agent handles all conversations.
- Service tracks \`request_id -> route\` and forwards each \`assistant_output\` by \`request_id\`.
- Good default when you want global shared context.

2) Scoped agent per conversation:
- Derive a stable task_id from \`{namespace, conversation_id}\` and upsert that agent.
- Use \`scopedAgent({ namespace, key, ... })\` from \`core/agent.ts\` when you want this with minimal code.
- Each conversation gets isolated context; no cross-talk between concurrent users.
- Good when many parallel conversations need independent memory/behavior.

Both are generic and platform-agnostic. The route object can represent any external protocol (chat/thread/session/request/channel/device/etc.).`
}

builder.add({ id: "managed-contract", priority: 500, content: managedContractBlock() })
builder.add({ id: "task-api", priority: 450, content: taskApiBlock() })
builder.add({ id: "services-contract", priority: 400, content: servicesContractBlock() })
builder.add({ id: "bridge-pattern", priority: 350, content: bridgePatternBlock() })
builder.add({ id: "output-routing", priority: 300, content: outputRoutingBlock() })
builder.add({ id: "routing-strategy", priority: 250, content: routingStrategyBlock() })

export function buildHarnessPrompt(extra?: string) {
  if (extra && extra.trim().length > 0) {
    builder.add({
      id: "managed-extra",
      priority: 0,
      content: extra.trim(),
    })
  }
  return builder.build()
}

if (import.meta.main) {
  console.log(buildHarnessPrompt())
}
